#!/usr/bin/env perl

use warnings;
use strict;

my $home = $ENV{URB_HOME};

die "\$URB_HOME($home) is not a directory" unless -d $home;

my %scmds;
my ($scmd, @arg) = @ARGV;
my $tgt  = "urb-$scmd";
for my $d (split /:/, $ENV{PATH}) {
  chdir $d;
  if (-x $tgt) {
    exec { $tgt } ($tgt, @arg);
  }
  
  my @cmds = grep { -x $_ } glob('urb-*');
  @scmds{@cmds} = ();
}

print "Available subcommands:\n";
print "  $_\n" for (map { s/^urb-//; $_ } keys %scmds);
exit 1;
