#!/usr/bin/env perl

use warnings;
use strict;

my $path = join '/', ($ENV{URB_HOME}, @ARGV);
if (-d $path) {
  system "ls '$path'";
  exit 1;
}

$path =~ s|/([^/]*)$|.$1|;
if (-f $path) {
  system "ls '$path'";
  exit 0;
}

exit 2;
