#!/usr/bin/env perl

use warnings;
use strict;

my $cmd = join ' ', (qw(urb ls pub docs), @ARGV, 'md');
my $pat = `$cmd`;
chomp $pat;

if ($? == 0) {
  system { 'urb' } (qw(urb ls pub docs), @ARGV);
  exec "ronn -r --pipe '$pat' 2> /dev/null | man -l -"
}
elsif ($? == 1) {
  exec 'urb', (qw(urb ls pub docs), @ARGV);
}
else {
  print "$pat\n";
  exit 0;
}
